# Generated by Django 3.2.13 on 2022-10-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221014_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
